#!/usr/bin/python
import urllib
from bs4 import BeautifulSoup
import cfscrape

scraper = cfscrape.create_scraper() 
url= raw_input('Enter a url: ')
html= scraper.get('http://www.textise.net/showText.aspx?strURL=' + url).content 
soup = BeautifulSoup(html)

for script in soup(["script", "style"]):
    script.extract()    # rip it out

text = soup.get_text()

lines = (line.strip() for line in text.splitlines())
superSplit= (phrase.strip() for line in lines for phrase in line.split("  "))
text = '\n'.join(part for part in superSplit if part)

print(text)
